/* This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#ifndef __GNOME_CANVAS_MARSHAL_MARSHAL_H__
#define __GNOME_CANVAS_MARSHAL_MARSHAL_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* VOID:OBJECT,INT,INT,INT,INT (../../libgnomecanvas/gnome-canvas-marshal.list:1) */
extern
void gnome_canvas_marshal_VOID__OBJECT_INT_INT_INT_INT (GClosure     *closure,
                                                        GValue       *return_value,
                                                        guint         n_param_values,
                                                        const GValue *param_values,
                                                        gpointer      invocation_hint,
                                                        gpointer      marshal_data);

/* BOOLEAN:BOXED (../../libgnomecanvas/gnome-canvas-marshal.list:2) */
extern
void gnome_canvas_marshal_BOOLEAN__BOXED (GClosure     *closure,
                                          GValue       *return_value,
                                          guint         n_param_values,
                                          const GValue *param_values,
                                          gpointer      invocation_hint,
                                          gpointer      marshal_data);


G_END_DECLS

#endif /* __GNOME_CANVAS_MARSHAL_MARSHAL_H__ */
