.TH "evolution-rss" 1
.SH NAME
evolution-rss \- Evolution RSS Reader Plugin
.SH SYNOPSIS
.B evolution-rss
.SH DESCRIPTION
This is an evolution plugin which enables evolution to read rss feeds.
.TP
You are able to have RSS in same place as mails,
eliminating the need of having a separate RSS reader since a RSS Article
is like an email message.
.TP
Evolution RSS can display an article using summary view or HTML view.
