
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#ifndef __E_SHELL_ENUM_TYPES_H__
#define __E_SHELL_ENUM_TYPES_H__

#include <glib-object.h>

G_BEGIN_DECLS
/* enumerations from "../../shell/e-shell.h" */
GType e_shell_quit_reason_get_type (void);
#define E_TYPE_SHELL_QUIT_REASON (e_shell_quit_reason_get_type())
G_END_DECLS

#endif /* __E_SHELL_ENUM_TYPES_H__ */

/* Generated data ends here */

