#!/bin/sh

prefix=/MSYS2/mingw64
exec_prefix=${prefix}

PATH=/MSYS2/mingw64/bin:/usr/gnome/bin:${PATH}
GNOME2_PATH=/MSYS2/mingw64:/usr/gnome
LD_LIBRARY_PATH=/MSYS2/mingw64/lib:/usr/gnome/lib:${LD_LIBRARY_PATH}

export LD_LIBRARY_PATH GNOME2_PATH PATH

exec ${exec_prefix}/libexec/evolution-2.32 "$@"

